phony:
  - clean
  - train
  - test
  - validate
  - deploy

recipes:
  
  default-recipe: &rec00 'python $0'
  
  wrapped-recipe: &rec01
    - 'source activate py36'
    - *rec00
    - 'source deactivate'

  clean-recipe: &rec02 'rm -f *.pkl *.txt'

make:
  
  deploy:
    meta-data:
      - version.v
    scripts:
      - deploy.py
    tasks:
      - validate
    models:
      - intermediary.pkl
  
  test:
    meta-data:
      - model_accuracy.txt
  
  train:
    models:
      - intermediary.pkl
  
  validate:
    meta-data:
      - shared.py
      - model_accuracy.txt
    scripts:
      - validate.py
    models:
      - intermediary.pkl
    data:
      - clean_testing_tweets.pkl
    test:
      - deployflag.txt
    recipe: *rec01
  
  model_accuracy.txt:
    meta-data:
      - shared.py
    scripts:
      - test_model.py
    models:
      - intermediary.pkl
    data:
      - clean_testing_tweets.pkl
    recipe: *rec01

  intermediary.pkl:
    meta-data:
      - shared.py
    scripts:
      - train_model.py
    data:
      - clean_training_tweets.pkl
    recipe: *rec01

  clean_testing_tweets.pkl:
    meta-data:
      - shared.py
    scripts:
      - cleaner.py
    args:
      - te
    data:
      - testing_tweets.csv
    recipe: *rec01

  clean_training_tweets.pkl:
    meta-data:
      - shared.py
    scripts:
      - cleaner.py
    args:
      - tr
    data:
      - training_tweets.csv
    recipe: *rec01

  testing_tweets.csv:
    meta-data:
      - credentials.py
    scripts:
      - crawler.py
    args:
      - te
    recipe: *rec01

  training_tweets.csv:
    meta-data:
      - credentials
    scripts:
      - crawler.py
    args:
      - tr
    recipe: *rec01

  clean:
    recipe: *rec02
