#!/usr/bin/env zsh
rm -rf ~/.flor/complete_iris*;
rm -rf /var/folders/9k/v6q2q7jd03qfr1v6rp7tvvk40000gn/T/florist*;
set -e;
conda env remove --name flor;
pip uninstall pyflor -y;
python setup.py install

